### ISSUE TITLE
Styling Portlets Framework

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#144]
## Rationale

The Meeds Layout Manager enables different options to customize pages and portlets:
- page design: background, full window
- sections types: dynamic, fixed
- section styling: background
- portlet styling: border, background, fixed height

Considering it, we identified we needed to work on a global review of portlets (cf. MIP #135 )

Before working on such a cleanup, we suggest to implement a framework so we can variabilize such items to then apply it to each portlet. This will help other team to do the cleanup.

### Top User Stories

**Precision: only content portlets (snv, link, image) and portlets provided in the dashboard page (AKA overview) will be tested during this implementation to test it out**

This framework must help us to manage:
1. Height for portlet:
- if fixed section, then whole height of the selected zone is applied to the portlet
- if dynamic AND fixed height applied to the portlet, then height selected
- if dynamic (no fixed height), then height is depending on the content to list (as currently)

2. Background for portlet:
- A background can be applied to the portlet and its content (including the listed items)
- In case the background applied is darker than text, propose by default a lighter text color for text in the portlet

3. text-style:
- If a background is applied, ability to update the text color to make sure it is ok for readability / accessibility
- Ability as well to set a custom size / style for texts depending on their attribute (title, header, body, subtitle)
- Default style for text are:
- [ ] Title: 20px, bold, #20282C (regularColor)
- [ ] Header: 18px, #707070 (GreyLightenColor)
- [ ] Body: 16px, bold, #20282C (regularColor)
- [ ] Subtitle: 12px, #707070 (GreyLightenColor)

<img width="235" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/e128afae-12ac-4964-bf94-c65dffbbf24c">

4. General Branding options
As all these items will be variabilized in a global framework, we suggest to provide new options to set default styling.

Hence, from the branding options (theme page), we would be able to:
- As an admin, I can setup the default page design (full window or not). Of course, I can still go against this decision from the page design edition
- As an admin, I can update the default background

5. Platform Styling Review
All pages are reviewed in order to apply these styling characteristics.
As for instance:
- any messages text will get the body style
- any specific activity like link, news will get the title style for title, and subtitle for description / summary
- any app's header will get the header style
- any column's header of tables will get the header style
- any timestamp, subtitle, will get the subtitle style

And some specific style is applied for few items:
- menu item (left nav / tabs): body + font-weight-bold
- menu title (topbar logo, user display name, site name): body + font-weight-bold
Everything is detailed there: https://builders.meeds.io/portal/g/:spaces:developers/developers/notes/526

#### Gamification
NA

#### Notifications
NA

#### Analytics
NA

#### Unified Search
NA

### Expected Volume & Performance

N/A

### Security 

The Branding Options has to remain modifiable by Administrators only.
The read/write of user's theme (dark/light) has to be accessible to current user only.

### Extensibility 

N/A

### Configurability 

The default branding options has to remain configurable through branding.less file.

### Upgradability

No data upgrade should be necessary in order to benifit from this feature.

### Existing Features

No change to apply on default branding primary, secondary and tertiary colors for now, which may not fit the dark mode.

### Feature Flags

N/A

### Other Non Functional Requirements

N/A

### Access

  - The portlets styling has to use the helpers classes in order to allow define branding colors
  - The portlets branding has to be distinct from general branding, thus each portlet has to be able to specify different values for font and background colors
  - To allow branding portlets content using a generic class, each portlet body has to add a class `application-body`. This class will define all customizable CSS branding properties, such as colors, heights, margins ...

### Services & processing

  - A `branding.less` has to be defined by theme to allow defining default colors in both modes: light and dark.
  - When accessing the Branding CSS `:root` element, a new path parameter has to be added in order to specify which theme is used
  - The `BrandingService` has to be updated consequently in order to allow processing both themes at startup time.

### Data and persistence
  - The user personal preference shouldn't be stored in database, but should be based on Browser `Local Storage` only in order to allow choosing the preferred theme by Device and by Browser.

**Comment by srenault-meeds** [comment]
Hi @margondicco , to check.
I can't display any UI samples for now. Indeed, it seems I have no more access to adobe XD old files

**Comment by margondicco** [comment]
Hello ok for me 

For the font : 
can we have in the list these fonts Marianne + spectral + Arial + Georgia
https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-de-l-identite-de-l-etat/typographie/


I would like to add these two points in general branding : 

- fix by default the left navigation (important point)
- hide the option "define your own home page" (nice to have)

Thank you

**Comment by srenault-meeds** [comment]
Ok I added these points to be studied.

**Comment by boubaker** [comment]
Ready for tech review by DAO members (eXo @rdenarie )

**Comment by rdenarie** [comment]
Ok for me on tech side.

@boubaker have you evaluate if it will have an impact on our codebase and our portlets, to apply when merging the feature ?

**Comment by boubaker** [comment]
> Ok for me on tech side.
> 
> @boubaker have you evaluate if it will have an impact on our codebase and our portlets, to apply when merging the feature ?

Yes, there will be changes to do. But as usual, to help you receiving the feature, we will consider changes to propose on eXo side. But just keep in mind that the changes in the context of this MIP will be on some portlets only to prepare a framework, and all other portlets will be considered in Meeds-io/MIPs#135.
> Top User Stories
> Precision: only content portlets (snv, link, image and newslit) will be tested during this implementation to test it out

**Comment by srenault-meeds** [comment]
FYI @margondicco, @rdenarie we won't make any change to newslist for now as it is currently being used by your team.
For now, during this MIP, we will test our changes to following portlets:
- links
- snv
- image
- and any portlet proposed in the dashboard (AKA overview page)

**Comment by srenault-meeds** [comment]
Description updated + documentation link added

**Comment by srenault-meeds** [comment]
Feedbacks collected from exo-mips:
**< Only eXo >**
- Space settings tab: UI to adjust
- Document app: header of columns to adjust
- Document app: three dots menu to adjust
- CSS cleanup to do for messages / description to get the standard style
- Bottom bar visible to pages when adding border using custom css

Other items need to be worked but these are not blocker for now as another MIP will take care of app's cleanup. As for instance, few apps (tasks, agenda for exo, webconferencing, coediting admin pages don't get the style (background for example, we can custom)

**Comment by boubaker** [comment]
ACCs ready for test and PRs ready for review:
- Meeds PRs:
  - https://github.com/Meeds-io/gatein-portal/pull/929
  - https://github.com/Meeds-io/platform-ui/pull/807
  - https://github.com/Meeds-io/commons/pull/625
  - https://github.com/Meeds-io/social/pull/3943
  - https://github.com/Meeds-io/layout/pull/151
  - https://github.com/Meeds-io/gamification/pull/1647
  - https://github.com/Meeds-io/kudos/pull/508
  - https://github.com/Meeds-io/perk-store/pull/335
  - https://github.com/Meeds-io/wallet/pull/535
  - https://github.com/Meeds-io/app-center/pull/343
  - https://github.com/Meeds-io/analytics/pull/201
  - https://github.com/Meeds-io/notes/pull/1018
  - https://github.com/Meeds-io/content/pull/155
  - https://github.com/Meeds-io/poll/pull/156
  - https://github.com/Meeds-io/task/pull/406
  - https://github.com/Meeds-io/deeds-tenant/pull/76
  - https://github.com/Meeds-io/gamification-github/pull/179
  - https://github.com/Meeds-io/gamification-twitter/pull/85
  - https://github.com/Meeds-io/gamification-crowdin/pull/38
  - https://github.com/Meeds-io/meeds/pull/2239

- eXo PRs:
  - https://github.com/exoplatform/commons-exo/pull/40
  - https://github.com/exoplatform/ecms/pull/2376
  - https://github.com/exoplatform/mail-integration/pull/70
  - https://github.com/exoplatform/dlp/pull/56
  - https://github.com/exoplatform/agenda/pull/670
  - https://github.com/exoplatform/chat-application/pull/754
  - https://github.com/exoplatform/onlyoffice/pull/254
  - https://github.com/exoplatform/web-conferencing/pull/320
  - https://github.com/exoplatform/multifactor-authentication/pull/75
  - https://github.com/exoplatform/documents/pull/1269
  - https://github.com/exoplatform/processes/pull/378
  - https://github.com/exoplatform/automatic-translation/pull/84
  - https://github.com/exoplatform/data-upgrade/pull/238
  - https://github.com/exoplatform/platform-private-distributions/pull/379

**Comment by boubaker** [comment]
> ACCs ready for test and PRs ready for review

cc @margondicco @rdenarie

**Comment by margondicco** [comment]
Hello my feedbacks

**App doc**

![image](https://github.com/Meeds-io/MIPs/assets/31288011/ce57aa4f-2816-4610-80cc-47bb9aae480a)


could it be possible to reduce the width of the column name in order to display the whole label in french and Englishfor the column last upddate ?

The style of the menu on the 3dots and the right clic is different

+ some UI glitches (buttons color, text alignement but it isn't blocker (cc @Julien-Dubois-eXo we should deal with theses points)

**Settings**

![image](https://github.com/Meeds-io/MIPs/assets/31288011/ed050783-36c6-4b56-b5e9-65657b53a4e3)

alignement issue.

**Newslist fixed height issue**

1. edit the page, define a fixed height for some app. publish. Issue : only the height of the last app edited is updated
2. set a height greater than the normal height of the newslist template. We have an unnecessary scroll bar
![image](https://github.com/Meeds-io/MIPs/assets/31288011/9f711fc4-cd9b-46c1-a06b-17876a51b156)

**Comment by srenault-meeds** [comment]
Thanks.

Regarding Document, I agree your team must deal with these issues. Indeed, we want to avoid functional change (auto width, truncation for doc names, etc.). Same for three dots, color applied to icons go against the policy regarding it. In fact, an override is done to this icons and changes the default icon color.

Regarding settings in a space, ok we'll take care of it.
Regarding fixed height, ok I don't reproduce it on meeds side (only for exo-mips). We will study this
Regarding newslist and scroll, I reproduce it as well. We will study this

**Comment by rdenarie** [comment]
Some feedbacks on my side : 

1. In document app, the Add menu change a lot : 
- icon + (before "New") size
- icon size in the menu
- icon color in the menu
- text align in the menu

To compare : 
Before : 
![Image](https://github.com/Meeds-io/MIPs/assets/807839/35298459-fa4b-4928-85d6-e562d53c7ede)

After 
![Image](https://github.com/Meeds-io/MIPs/assets/807839/7d10a8de-46da-43f7-ac29-b2281042574c)

2. In space settings :
We loose margin between components  (not sure if it is the same feedback as Morgan)
![Image](https://github.com/Meeds-io/MIPs/assets/807839/3b297f38-309b-455f-b4ff-a2d2a5fe1ea1)


3. Constrast problem in administration breadcrumbs  
![Image](https://github.com/Meeds-io/MIPs/assets/807839/9779f186-1d5d-49ed-a996-28e72bf341d6)

4. In visio admin, there is a title which a very tiny size 
![Image](https://github.com/Meeds-io/MIPs/assets/807839/2d89828e-ac51-4ce0-a000-1bb3c581856b)

**Comment by srenault-meeds** [comment]
Thanks @rdenarie 

> In document app, the Add menu change a lot :

Yes, we have updated following the expected best practices:
- mdi icons was used
- not btn default was used
- not right color is used. A wrong color is applied to it, using darkgrey while you must use the uidefaulticon 
AND btw regarding three dots, you must see the same problem. We didn't do nothing as discussed with @margondicco 
We let your team align with expected standards.

> In space settings : We loose margin between components

Yes it is expected in fact

> Constrast problem in administration breadcrumbs

Can you be more precise?

> In visio admin, there is a title which a very tiny size

Indeed, we will study this

**Comment by rdenarie** [comment]
> Constrast problem in administration breadcrumbs
Can you be more precise?
![image](https://github.com/Meeds-io/MIPs/assets/807839/7a4b4861-b6a1-4ef5-84e0-262f6300139f)

The color for "Platform Settings" is 0,0,0,026
The background color is FFF
When checking it with a contrast checker (https://webaim.org/resources/contrastchecker/?fcolor=00000042&bcolor=FFFFFF) we have a ratio of 1,87:1, and we need at least 4.5:1 to bo compliant.

**Comment by srenault-meeds** [comment]
We used the same pattern as before. We plan to review each site one by one later in the summer. I suggest we review this during that time. 
Indeed the current MIP was overall the application of the styling framework and not the review of all sites and apps.

Any objection?

**Comment by rdenarie** [comment]
Thanks for your answers @srenault-meeds 

After that theses feedbacks in account, it is ok for me, you can process to the merge

**Comment by srenault-meeds** [comment]
Hello @margondicco @rdenarie 

- Alignement of space settings item: OK
- Style of "Video conference" label in webconf admin page: OK
- Setting height for different app and publishing it: OK

Regarding Scrollbar to newslist, it looks like the templates need to be reviewed one by one.
We suggest to fix/improve this outside this MIP as a maintenance issue.
IMO this is not blocker

I let you confirm. Thanks

**Comment by margondicco** [comment]
> 
> Regarding Scrollbar to newslist, it looks like the templates need to be reviewed one by one.
> We suggest to fix/improve this outside this MIP as a maintenance issue.
> IMO this is not blocker
>

Test ok for me
and ok for the fix on a dedicated issue for the newslists.

Thank you

cc @boubaker @srenault-meeds

**Comment by boubaker** [comment]
Meeds & eXo PRs merged to develop
